### ISSUE TITLE
Could this be a REST API? 

### ISSUE THREAD

**Issue by Flaque** [YIMBYdata/neighborhood#1]
This would be super useful in several other projects that aren't python related.

**Comment by dfings** [comment]
This is more RPC than REST, but maybe something this?

/sf/district?address=123%20Main%20St
/sf/district?address=123+Main+St
/sf/neighborhood?address=123%20Main%20St
/sf/neighborhood?address=123+Main+St

**Comment by Flaque** [comment]
RPC's cool too. That seems reasonable.

**Comment by dfings** [comment]
This is now a Dockerized server. Skylar will deploy it.
